package status

const (
	OK                    = "OK"
	CREATED               = "CREATED"
	BAD_REQUEST           = "BAD_REQUEST"
	UNAUTHORIZED          = "UNAUTHORIZED"
	FORBIDDEN             = "FORBIDDEN"
	NOT_FOUND             = "NOT_FOUND"
	UNPROCESSABLE_ENTITY  = "UNPROCESSABLE_ENTITY"
	EXPECTATION_FAILED    = "EXPECTATION_FAILED"
	INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"

	// custom status
	ALREADY_EXIST     = "ALREADY_EXIST"
	ALREADY_SIGNED_IN = "ALREADY_SIGNED_IN"
)
